---
deployment:
  tasks:
    - name: "Copy files to the server"
      copy:
        src: "/home/eahg1672/repositories/catourne-website/public"
        dest: "/home/eahg1672/marrantmaispastrop.fun"
        owner: "eahg1672"
        group: "eahg1672"
        mode: "0755"
        recursive: true
        force: true


